### ISSUE TITLE
 [channel_output_email#error] A smtp error occurred: <class 'smtplib.SMTPSenderRefused'> - (550, 'From header is missing, header is not RFC 5322 compliant', '')

### ISSUE THREAD

**Issue by mcomtzg** [thinkst/canarytokens-docker#134] opened 2023-02-11 00:58 UTC
Hello, any comments about this issue? 

I'm using user, password and TLS enable.

**Comment by jayjb** [comment] 2023-08-04 11:37
Hi @mcomtzg,

Thanks for getting in touch. Would you mind sharing some more information about your configuration? Maybe what your two configuration files look like.

**Comment by emmanuel-thinkst** [comment] 2023-08-21 11:38
Hi @mcomtzg 

Sorry for the late response. We have decided to close this issue because we reproduced a similar error as the one above with our own `SMTP` servers, and we did that by not specifying the `CANARY_ALERT_EMAIL_FROM_ADDRESS` environment variable in `switchboard.env`.

It's important to note that for our old canarytokens, the `CANARY_ALERT_EMAIL_FROM_ADDRESS` environment variable is required to use `SMTP`. Currently support for `SMTP` is a feature request for our latest `canarytokens`.

Please check if the error persists for you when specifying the `CANARY_ALERT_EMAIL_FROM_ADDRESS` environment variable in your Dockerized Canarytokens and if it does persist, feel free to inform us.

Please pull the latest changes from our master branch and run our Dockerized Canarytokens. And please feel free to reopen the issue with replication steps should the error persist for you. 

Thank You.

**Closed by emmanuel-thinkst** 2023-08-21 11:38 UTC
Labels: question
