### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by dirtdiver512** [thinkst/canarytokens-docker#54] opened 2020-02-27 17:02 UTC
Ok so not new to linux but new to docker.  I am trying to get this installed but running into what i assume is a basic issue.   I run all the install commands but when I try to start this I get the below:

ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

canary@canary:~/canarytokens/canarytokens-docker$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
canary@canary:~/canarytokens/canarytokens-docker$

**Comment by dirtdiver512** [comment] 2020-02-28 00:50
OK so I messed with this all day and got no where....what platform are you guys using?  I tried Ubuntu 18 and it didnt like that.  So I have been messing with Ubuntu 16 and it really hates the old version of python on there....even if I update it to 3.5 I still get a lot of errors.

**Comment by Blason** [comment] 2020-02-28 02:37
Should not be an issue, it worked for me on Ubuntu 18.04 only thing you need to change canarytokens/Dockerfile FROM ubuntu:16.04 to FROM ubuntu:18.04

**Comment by jayjb** [comment] 2020-02-28 09:39
Hi @dirtdiver512,

Sorry to hear that you hitting some issues. Would you mind letting me know how you trying to run the canarytokens-docker? What OS? Just a few more details so I can try replicate and find a solution for you.

**Comment by dirtdiver512** [comment] 2020-02-28 17:43
Looks like it is crashing right around the pip and python stuff.  It s fresh install of Ubuntu 16.  Including the log during install.
[canary-install.zip](https://github.com/thinkst/canarytokens-docker/files/4268327/canary-install.zip)

**Comment by dirtdiver512** [comment] 2020-02-28 17:44
I have tried the install instruction here and on :

https://zeltser.com/honeytokens-canarytokens-setup/

**Comment by dirtdiver512** [comment] 2020-02-28 17:55
zip file was empty...sorry
[canary-install.log](https://github.com/thinkst/canarytokens-docker/files/4268362/canary-install.log)

**Comment by dirtdiver512** [comment] 2020-02-28 19:09
for ubutnu 18 i changed that file and get to this point:

canary@canary-18:~/canarytokens-docker$ docker-compose up
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.


canary@canary-18:~/canarytokens-docker$ docker-machine start default
Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.



canary@canary-18:~/canarytokens-docker$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
canary@canary-18:~/canarytokens-docker$

**Comment by jayjb** [comment] 2020-03-01 06:06
Hi @dirtdiver512,

What OS are you trying to run docker on? That way I can try reproduce the issue and help you quickly. 

Thanks for sending the logs and info. I want to get you up and running as soon as possible.

**Comment by pisces-period** [comment] 2020-03-05 14:09
@jayjb the image-build process fails due to incompatibility w/ Python 2.7 (which is now deprecated). Updating base-image to Ubuntu 18.04 seems to fix this problem. 

However, using a full-blown OS as a base-image seems a bit overkill.

**Comment by jayjb** [comment] 2020-03-30 13:17
Hi @pisces-period, @dirtdiver512,

We have updated the docker images. Please give them a go and let me know if you have any issues.

**Comment by jayjb** [comment] 2021-08-20 06:34
Closing this issue.

**Closed by jayjb** 2021-08-20 06:34 UTC
